theme = "onedark"

[editor]
# idle-timeout = 100
auto-format = true
completion-replace = true
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-signature-help-docs = false
goto-reference-include-declaration = false

[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
c=["trim_selections", "change_selection"]
a=["append_mode", "collapse_selection"]
esc=["collapse_selection", "keep_primary_selection"]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"
h=["insert_mode", "collapse_selection"]
H="insert_at_line_start"
l="open_below"
L="open_above"
k="move_next_word_end"
K="move_next_long_word_end"
j="search_next"
J="search_prev"
"C-n"="jump_backward"
"C-o"="jump_forward"
"C-e"="half_page_down"
"C-i"="half_page_up"
"A-n"="shrink_selection"
"A-o"="expand_selection"
O="no_op"
q={q=":write-quit-all"}

[keys.normal.space]
t=":write"
c="command_mode"
l=":buffer-close"

[keys.normal.g]
n="goto_line_start"
o="goto_line_end"

[keys.normal.space.w]
n="jump_view_left"
e="jump_view_down"
i="jump_view_up"
o="jump_view_right"

[keys.normal.C-w]
n="jump_view_left"
e="jump_view_down"
i="jump_view_up"
o="jump_view_right"

[keys.insert]
ret=["insert_newline", "collapse_selection"] # There is an odd edge case when pressing enter at the end of a line
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
esc=["collapse_selection", "keep_primary_selection", "normal_mode"]
n="extend_char_left"
e="extend_line_down"
i="extend_line_up"
o="extend_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="extend_next_word_end"
K="extend_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.z]
e="scroll_down"
i="scroll_up"

[keys.normal.Z]
e="scroll_down"
i="scroll_up"
